version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rosblocks-backend
    ports:
      - "8000:8000"
    volumes:
      - ./scripts/generated:/ros2_ws/src/sample_pkg/sample_pkg
    networks:
      - rosblocks-network

  ros2:
    image: ros:jazzy-ros-base
    container_name: ros2-jazzy
    environment:
      - DISPLAY=${DISPLAY}  # Permitir soporte gráfico para turtlesim
    volumes:
      - ./scripts/generated:/ros2_ws/src/sample_pkg/sample_pkg
      - /tmp/.X11-unix:/tmp/.X11-unix  # Soporte gráfico
    networks:
      - rosblocks-network
    working_dir: /ros2_ws
    command: >
      bash -c "apt update && apt install -y ros-jazzy-turtlesim &&
               source /opt/ros/jazzy/setup.bash &&
               colcon build --symlink-install &&
               tail -f /dev/null"

networks:
  rosblocks-network:
    driver: bridge
