version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rosblocks-backend
    ports:
      - "8000:8000"
    volumes:
      - ./scripts/generated:/ros2_ws/src/sample_pkg/sample_pkg
      - /var/run/docker.sock:/var/run/docker.sock
