services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rosblocks-backend
    ports:
      - "8000:8000"
      - "8080:8080"
      - "5900:5900"
    volumes:
      - ./scripts/generated:/ros2_ws/src/sample_pkg/sample_pkg
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    stdin_open: true