version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rosblocks-backend
    ports:
      - "8000:8000"
    volumes:
      - ./scripts/generated:/ros2_ws/src/sample_pkg/sample_pkg
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rosblocks-network
    tty: true
    stdin_open: true
    depends_on:
      - novnc

  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=300
      - DISPLAY_HEIGHT=300
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - rosblocks-network

networks:
  rosblocks-network:
    driver: bridge
