FROM osrf/ros:jazzy-desktop-full

# Update package lists and install necessary packages including python3-venv
RUN apt-get update && apt-get install -y \
    git \
    wget \
    python3-pip \
    python3-venv \
    vim \
    docker.io

# Create a virtual environment and install the required version of setuptools
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --upgrade pip && \
    /opt/venv/bin/pip install setuptools==58.2.0

ENV DISPLAY=novnc:0.0